### ISSUE TITLE
enable https on parlgov.org

### ISSUE THREAD

**Issue by waldenn** [hdigital/parlgov-snippets#10]
Hi,

I would like to deeplink and iframe-embed your project site (from https://conze.pt), but that requires (due to modern browser restrictions) that the website implements HTTPS.

This only takes a few minutes to setup using Lets Encrypt: https://letsencrypt.org/getting-started/

Hope you can do that. Thanks for an interesting project.

**Comment by hdigital** [comment]
the current static version of the page is on https (see https://parlgov.org)

a new future version of the dynamic will be on https as well (but no schedule yet)
