### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by raffaelemancuso** [hdigital/parlgov-snippets#12]
In this page: https://www.parlgov.org/data-info/

The link to the current version of the dataset: https://parlgov.org/data/parlgov-development_csv-utf-8/

doesn't work, it returns a 403 forbidden error

**Comment by hdigital** [comment]
@raffaem you need to add the name of the ParlGov data file you want to access.

The data files are available at the location (e.g. [parties]([parties](https://parlgov.org/data/parlgov-development_csv-utf-8/view_party.csv)) but no index of the availble files is provided at the url.
